apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "junedwork@hotmail.com"
    privateKeySecretRef:
      name: issuer
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z071626911B43BHE81W1J #this must be updated with the current hostedZoneID in order for it to work
          region: eu-west-2
      selector:
        dnsZones:
        - "lab.juned.co.uk"
    - http01:
        ingress:
          class: nginx