apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default

  source:
    repoURL: "https://github.com/JunedConnect/lab-eks-project.git"
    targetRevision: dev #change this back to HEAD or main as this is the branch that argocd will be using
    path: argocd/apps

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: myapp-ns
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true